In [8]:
import torch

In [9]:
t = torch.randn(1, 2, 3)

In [10]:
t.permute(2, 1)

RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 3 is not equal to len(dims) = 2

In [ ]:
t.transpose()

In [2]:
from torch import nn

In [28]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.mlp = nn.Sequential(
            nn.Linear(64, 128),
            nn.Linear(128, 256),
        )

    def forward(self, x):
        return self.mlp(x)

In [29]:
model = Model()

In [35]:
model.mlp[0].bias.var()

tensor(0.0056, grad_fn=<VarBackward0>)

In [15]:
model.state_dict()

OrderedDict([('mlp.0.weight',
              tensor([[ 0.3318, -0.1389, -0.0195,  0.2322],
                      [ 0.0692,  0.2708, -0.4090,  0.3156],
                      [-0.4571, -0.2235, -0.4856, -0.1570],
                      [-0.3014, -0.1501, -0.4275,  0.3352],
                      [-0.0368, -0.2275, -0.1098,  0.1384],
                      [ 0.4209, -0.0670, -0.4589,  0.1089],
                      [ 0.2612, -0.1036, -0.1214,  0.0951],
                      [-0.2469,  0.1862, -0.2558, -0.2332]])),
             ('mlp.0.bias',
              tensor([ 0.2364, -0.3161, -0.0384, -0.2221,  0.2470, -0.3906,  0.2637, -0.2800])),
             ('mlp.1.weight',
              tensor([[ 0.0470,  0.3498, -0.1135,  0.2643,  0.0062, -0.3066,  0.3084,  0.1004],
                      [-0.0507,  0.3232, -0.3410, -0.2666, -0.1611, -0.0957,  0.2270,  0.1157],
                      [-0.0565, -0.0062, -0.0649,  0.1776, -0.0972, -0.0572, -0.0673, -0.2773],
                      [ 0.1321, -0.0566, -0.

In [7]:
nn.TransformerDecoderLayer.forward?

Signature:
nn.TransformerDecoderLayer.forward(
    self,
    tgt: torch.Tensor,
    memory: torch.Tensor,
    tgt_mask: Optional[torch.Tensor] = None,
    memory_mask: Optional[torch.Tensor] = None,
    tgt_key_padding_mask: Optional[torch.Tensor] = None,
    memory_key_padding_mask: Optional[torch.Tensor] = None,
    tgt_is_causal: bool = False,
    memory_is_causal: bool = False,
) -> torch.Tensor
Docstring:
Pass the inputs (and mask) through the decoder layer.

Args:
    tgt: the sequence to the decoder layer (required).
    memory: the sequence from the last layer of the encoder (required).
    tgt_mask: the mask for the tgt sequence (optional).
    memory_mask: the mask for the memory sequence (optional).
    tgt_key_padding_mask: the mask for the tgt keys per batch (optional).
    memory_key_padding_mask: the mask for the memory keys per batch (optional).
    tgt_is_causal: If specified, applies a causal mask as ``tgt mask``.
        Default: ``False``.
        ``tgt_is_causal`` 

In [87]:
torch.manual_seed(42)
a = torch.randn(2, 3, 5); a.requires_grad = True
a.sum(dim=(1,2), keepdims=True).sum().backward()

In [88]:
a.grad

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [72]:
a.softmax(dim=-1)

tensor([[[0.4334, 0.2792, 0.1553, 0.0077, 0.1244],
         [0.0409, 0.1345, 0.0282, 0.0662, 0.7302],
         [0.3256, 0.1185, 0.2328, 0.2756, 0.0475]],

        [[0.1026, 0.0319, 0.0533, 0.1020, 0.7101],
         [0.3380, 0.1607, 0.1073, 0.3421, 0.0518],
         [0.2200, 0.0337, 0.0446, 0.0227, 0.6790]]],
       grad_fn=<SoftmaxBackward0>)

In [73]:
a.grad.fill_(0.0)
a.softmax(dim=-1).sum().backward()

In [74]:
a.grad

tensor([[[5.1666e-08, 3.3287e-08, 1.8515e-08, 9.1609e-10, 1.4825e-08],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [2.6223e-08, 4.0197e-09, 5.3114e-09, 2.7097e-09, 8.0946e-08]]])

In [ ]:
torch.autograd.functional.vjp()

In [32]:
def softmax(t: torch.Tensor) -> torch.Tensor:
    return torch.softmax(t, -1)

In [35]:
v = a[0, :1]

In [36]:
J = torch.autograd.functional.jacobian(softmax, v)
J

tensor([[[[ 0.2456, -0.1210, -0.0673, -0.0033, -0.0539]],

         [[-0.1210,  0.2013, -0.0434, -0.0021, -0.0347]],

         [[-0.0673, -0.0434,  0.1312, -0.0012, -0.0193]],

         [[-0.0033, -0.0021, -0.0012,  0.0076, -0.0010]],

         [[-0.0539, -0.0347, -0.0193, -0.0010,  0.1089]]]])

torch.Size([5, 5])

In [45]:
torch.ones_like(v) @ J[0, :, 0]

tensor([[2.9802e-08, 1.4901e-08, 1.8626e-08, 9.3132e-10, 1.4901e-08]])

In [90]:
torch.manual_seed(1337)
B,T,C = 4,8,2
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [91]:
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow = wei@x

In [94]:
xbow.shape

torch.Size([4, 8, 2])

In [4]:
import torch

torch.manual_seed(42)
a = torch.randn(3, 4, requires_grad=True)
a

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]], requires_grad=True)

In [25]:
v = a.var(dim=[0, 1], keepdim=True)
v

tensor([[0.6504]], grad_fn=<VarBackward0>)

In [6]:
v.mean().backward()

In [8]:
a.grad

tensor([[ 2.3137e-02, -2.3059e-02,  4.1968e-04, -4.9795e-04],
        [-2.6402e-01, -5.5907e-02,  4.7621e-01, -1.5628e-01],
        [-1.2591e-02, -5.5770e-02,  3.6860e-03,  6.4676e-02]])